export const surpriseMePrompts = [
    "A futuristic cityscape at sunset with flying cars and neon lights",
    "A mystical forest with glowing mushrooms and floating spirits",
    "A cyberpunk samurai standing on a rooftop under a rainy sky",
    "An ancient temple hidden deep in the jungle, covered in vines",
    "A cute robot making pancakes in a cozy kitchen",
    "A dragon soaring over a snowy mountain peak during sunrise",
    "A surreal dream world with floating islands and upside-down waterfalls",
    "A retro 80s-style space scene with astronauts and neon planets",
    "A warrior in golden armor battling a giant shadow monster",
    "A magical library with books that float and whisper secrets",
    "A giant whale swimming through the clouds in a pastel sky",
    "A tiny astronaut exploring a flower garden on an alien planet",
    "A medieval castle floating in the sky, surrounded by storm clouds",
    "A steampunk inventor working in a cluttered workshop with gears and machines",
    "A secret underwater city with glowing coral buildings",
    "A peaceful Zen garden with koi fish swimming in a crystal-clear pond",
    "A neon-lit alleyway in a futuristic cyberpunk city",
    "A spaceship landing on a mysterious exoplanet with colorful landscapes",
    "A samurai cat warrior in traditional armor holding a katana",
    "A young witch brewing a potion in a magical forest, surrounded by glowing creatures"
];
