import React, {useEffect} from 'react'

import {Loader, Card, FormField} from '../components'

const RenderCards = ({data, title}) => {
    if (data?.length > 0) return data.map((post) => <Card key={post._id} {...post}/>)

    return (
        <h2 className={"mt-5 font-bold text-[#6449ff] text-xl uppercase"}>
            {title}
        </h2>
    )
}

const Home = () => {
    const [loading, setLoading] = React.useState(false)
    const [allPosts, setAllPosts] = React.useState(null)

    const [searchText, setSearchText] = React.useState('')
    const [searchedResults, setSearchedResults] = React.useState(null)
    const [searchTimeout, setSearchTimeout] = React.useState(null)

    useEffect(() => {
        const fetchPosts = async () => {
            setLoading(true)

            try {
                // http://localhost:5000/api/v1/post
                const response = await fetch('https://imagegenerator-ai.onrender.com/api/v1/post', {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    timeout: 60000
                })

                if (response.ok) {
                    const result = await response.json();
                    // Reverse in order to show latest post ast the top
                    setAllPosts(result.data.reverse());
                }
            }
            catch (error) {
                alert(error)
            }
            finally {
                setLoading(false)
            }
        }

        fetchPosts()
    }, [])

    const handleSearchChange = (e) => {
        clearTimeout(searchTimeout)

        setSearchText(e.target.value);

        setSearchTimeout(
            setTimeout(() => {
                const searchResults = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()))

                setSearchedResults(searchResults)
            }, 500)
        )
    }

    return (
        <section className={"max-w-7xl mx-auto"}>
            <div>
                <h1 className={"font-extrabold text-[#222328] text-[32px]"}>
                    The Community Showcase
                </h1>
                <p className={"mt-2 text-[#666e75] text-[16px] max-w-[500px]"}>
                    Browse through a collection of imaginative and visually stunning images generated by the FLUX.1-schnell
                </p>
            </div>

            <div className={"mt-16"}>
                <FormField
                    labelName={"Search Posts"}
                    type={"text"}
                    name={"text"}
                    placeholder={"Search Posts"}
                    value={searchText}
                    handleChange={handleSearchChange}
                />
            </div>

            <div className={"mt-10"}>
                {loading ? (
                    <div className={"flex justify-center items-center"}>
                        <Loader/>
                    </div>
                ) : (
                    <>
                        {searchText && (
                            <h2 className={"font-medium text-[#666e75] text-xl md-3"}>
                                Showing results for <span className={"text-[#222328]"}>{searchText}</span>
                            </h2>
                        )}

                        <div className={"grid lg:grid-col-4 sm:grid-col-3 xs:grid-col-2 grid-cols-1 gap-3"}>
                            {searchText ? (
                                <RenderCards data={searchedResults} title={"No search results found"}/>
                            ) : (
                                <RenderCards data={allPosts} title={"No posts found"}/>
                            )}
                        </div>
                    </>
                )}
            </div>
        </section>
    )
}
export default Home
